name: Manual trigger workflow

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Name of resource group'
        required: true
        default: 'mcw-iac'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
            resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
            template: ./Hands-on-Lab/templates/deploy-vm-as-domain-member.json
            parameters: ./Hands-on-Lab/templates/deploy-vm-as-domain-member.parameters.json